### ISSUE TITLE
error when production build with webpack 5

### ISSUE THREAD

**Issue by kikyous** [jeerbl/webfonts-loader#135]
```js
        {
          test: /\.font\.js$/,
          use: [
            MiniCssExtractPlugin.loader,
            {
              loader: 'css-loader',
              options: {
                url: false
              }
            },
            "sass-loader",
            "webfonts-loader"
          ],
        },
```

ERROR in ./assets/fonts/app.font.js
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '/static/lms/static/app.6a3e74e57a949a7245be225b6a495b97.woff' in '/Users/admin/demo/assets/fonts'
    at finishWithoutResolve (/Users/admin/demo/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:293:18)
    at /Users/admin/demo/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/admin/demo/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/admin/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/admin/demo/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/admin/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/admin/demo/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/admin/demo/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/admin/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/admin/demo/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/admin/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/admin/demo/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/admin/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/admin/demo/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/admin/demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/admin/demo/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at processResult (/Users/admin/demo/node_modules/webpack/lib/NormalModule.js:598:19)
    at /Users/admin/demo/node_modules/webpack/lib/NormalModule.js:692:5
    at /Users/admin/demo/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/admin/demo/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/admin/demo/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Users/admin/demo/node_modules/css-loader/dist/index.js:155:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

1 ERROR in child compilations
webpack 5.19.0 compiled with 2 errors in 1025704 ms
error Command failed with exit code 1.

**Comment by kikyous** [comment]
but build sucess if replace MiniCssExtractPlugin.loader with "style-loader"
