### ISSUE TITLE
Array buffer allocation failed

### ISSUE THREAD

**Issue by YonathanB** [jeerbl/webfonts-loader#61]
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at Object.<anonymous> (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\ttf2woff2\jssrc\ttf2woff2.js:1:23296)
    at Module._compile (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\ttf2woff2\jssrc\index.js:3:27)
    at Module._compile (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\ttf2woff2\src\index.js:6:20)
    at Module._compile (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\webfonts-generator\src\generateFonts.js:8:17)
    at Module._compile (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\webfonts-generator\src\index.js:6:21)
    at Module._compile (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (c:\Workspaces\KramerNetwork\Dashboard\WebApplication\Client\application\node_modules\webfonts-loader\index.js:2:25)
```

Any idea?

**Comment by YonathanB** [comment]
I've upgraded my node and now everything is ok
